apiVersion: v1
kind: Service
metadata:
  labels:
    service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: pgadmin
status:
  loadBalancer: {}
