apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira-clone
    tier: backend
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-clone
      tier: backend
      service: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: jira-clone
        tier: backend
        service: backend
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: backend-config
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: backend-config
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: backend-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: backend-config
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: backend-config
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: backend-config
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: backend-config
          image: jiraclone/backend
          imagePullPolicy: Never
          name: backend-jira-clone
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
