apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
  namespace: mi-espacio
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: backend
